/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FailRouteImport } from './routes/fail'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TestRouteImport } from './routes/test'
import { Route as IntroIndexRouteImport } from './routes/intro.index'
import { Route as IntroSessionIdRouteImport } from './routes/intro.$sessionId'
import { Route as IntroSessionIdIndexRouteImport } from './routes/intro.$sessionId.index'
import { Route as IntroSessionIdDownloadRouteImport } from './routes/intro.$sessionId.download'
import { Route as IntroSessionIdLocationRouteImport } from './routes/intro.$sessionId.location'
import { Route as IntroLocationCompanyIdRouteImport } from './routes/intro.location.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FailRoute = FailRouteImport.update({
  id: '/fail',
  path: '/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroIndexRoute = IntroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntroRoute,
} as any)
const IntroSessionIdRoute = IntroSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => IntroRoute,
} as any)
const IntroSessionIdIndexRoute = IntroSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntroSessionIdRoute,
} as any)
const IntroSessionIdDownloadRoute = IntroSessionIdDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => IntroSessionIdRoute,
} as any)
const IntroSessionIdLocationRoute = IntroSessionIdLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => IntroSessionIdRoute,
} as any)
const IntroLocationCompanyIdRoute = IntroLocationCompanyIdRouteImport.update({
  id: '/location/$companyId',
  path: '/location/$companyId',
  getParentRoute: () => IntroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fail': typeof FailRoute
  '/intro': typeof IntroRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/intro/$sessionId': typeof IntroSessionIdRouteWithChildren
  '/intro/': typeof IntroIndexRoute
  '/intro/$sessionId/download': typeof IntroSessionIdDownloadRoute
  '/intro/$sessionId/location': typeof IntroSessionIdLocationRoute
  '/intro/location/$companyId': typeof IntroLocationCompanyIdRoute
  '/intro/$sessionId/': typeof IntroSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fail': typeof FailRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/intro': typeof IntroIndexRoute
  '/intro/$sessionId/download': typeof IntroSessionIdDownloadRoute
  '/intro/$sessionId/location': typeof IntroSessionIdLocationRoute
  '/intro/location/$companyId': typeof IntroLocationCompanyIdRoute
  '/intro/$sessionId': typeof IntroSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fail': typeof FailRoute
  '/intro': typeof IntroRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/success': typeof SuccessRoute
  '/test': typeof TestRoute
  '/intro/$sessionId': typeof IntroSessionIdRouteWithChildren
  '/intro/': typeof IntroIndexRoute
  '/intro/$sessionId/download': typeof IntroSessionIdDownloadRoute
  '/intro/$sessionId/location': typeof IntroSessionIdLocationRoute
  '/intro/location/$companyId': typeof IntroLocationCompanyIdRoute
  '/intro/$sessionId/': typeof IntroSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fail'
    | '/intro'
    | '/refund-policy'
    | '/success'
    | '/test'
    | '/intro/$sessionId'
    | '/intro/'
    | '/intro/$sessionId/download'
    | '/intro/$sessionId/location'
    | '/intro/location/$companyId'
    | '/intro/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fail'
    | '/refund-policy'
    | '/success'
    | '/test'
    | '/intro'
    | '/intro/$sessionId/download'
    | '/intro/$sessionId/location'
    | '/intro/location/$companyId'
    | '/intro/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/fail'
    | '/intro'
    | '/refund-policy'
    | '/success'
    | '/test'
    | '/intro/$sessionId'
    | '/intro/'
    | '/intro/$sessionId/download'
    | '/intro/$sessionId/location'
    | '/intro/location/$companyId'
    | '/intro/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FailRoute: typeof FailRoute
  IntroRoute: typeof IntroRouteWithChildren
  RefundPolicyRoute: typeof RefundPolicyRoute
  SuccessRoute: typeof SuccessRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fail': {
      id: '/fail'
      path: '/fail'
      fullPath: '/fail'
      preLoaderRoute: typeof FailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro/': {
      id: '/intro/'
      path: '/'
      fullPath: '/intro/'
      preLoaderRoute: typeof IntroIndexRouteImport
      parentRoute: typeof IntroRoute
    }
    '/intro/$sessionId': {
      id: '/intro/$sessionId'
      path: '/$sessionId'
      fullPath: '/intro/$sessionId'
      preLoaderRoute: typeof IntroSessionIdRouteImport
      parentRoute: typeof IntroRoute
    }
    '/intro/$sessionId/': {
      id: '/intro/$sessionId/'
      path: '/'
      fullPath: '/intro/$sessionId/'
      preLoaderRoute: typeof IntroSessionIdIndexRouteImport
      parentRoute: typeof IntroSessionIdRoute
    }
    '/intro/$sessionId/download': {
      id: '/intro/$sessionId/download'
      path: '/download'
      fullPath: '/intro/$sessionId/download'
      preLoaderRoute: typeof IntroSessionIdDownloadRouteImport
      parentRoute: typeof IntroSessionIdRoute
    }
    '/intro/$sessionId/location': {
      id: '/intro/$sessionId/location'
      path: '/location'
      fullPath: '/intro/$sessionId/location'
      preLoaderRoute: typeof IntroSessionIdLocationRouteImport
      parentRoute: typeof IntroSessionIdRoute
    }
    '/intro/location/$companyId': {
      id: '/intro/location/$companyId'
      path: '/location/$companyId'
      fullPath: '/intro/location/$companyId'
      preLoaderRoute: typeof IntroLocationCompanyIdRouteImport
      parentRoute: typeof IntroRoute
    }
  }
}

interface IntroSessionIdRouteChildren {
  IntroSessionIdDownloadRoute: typeof IntroSessionIdDownloadRoute
  IntroSessionIdLocationRoute: typeof IntroSessionIdLocationRoute
  IntroSessionIdIndexRoute: typeof IntroSessionIdIndexRoute
}

const IntroSessionIdRouteChildren: IntroSessionIdRouteChildren = {
  IntroSessionIdDownloadRoute: IntroSessionIdDownloadRoute,
  IntroSessionIdLocationRoute: IntroSessionIdLocationRoute,
  IntroSessionIdIndexRoute: IntroSessionIdIndexRoute,
}

const IntroSessionIdRouteWithChildren = IntroSessionIdRoute._addFileChildren(
  IntroSessionIdRouteChildren,
)

interface IntroRouteChildren {
  IntroSessionIdRoute: typeof IntroSessionIdRouteWithChildren
  IntroIndexRoute: typeof IntroIndexRoute
  IntroLocationCompanyIdRoute: typeof IntroLocationCompanyIdRoute
}

const IntroRouteChildren: IntroRouteChildren = {
  IntroSessionIdRoute: IntroSessionIdRouteWithChildren,
  IntroIndexRoute: IntroIndexRoute,
  IntroLocationCompanyIdRoute: IntroLocationCompanyIdRoute,
}

const IntroRouteWithChildren = IntroRoute._addFileChildren(IntroRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FailRoute: FailRoute,
  IntroRoute: IntroRouteWithChildren,
  RefundPolicyRoute: RefundPolicyRoute,
  SuccessRoute: SuccessRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
